### ISSUE TITLE
Detailed information on single star

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/SWEETer-Cat#29]
It would be nice with some more detailed information about the star and its planet(s) on a page.

**Comment by DanielAndreasen** [comment]
This has been initiated in commit e274636d4731ab468a1

**Comment by DanielAndreasen** [comment]
Some stars have different planet name and star name in ExoplanetEU, therefore the merge does not work between SC and ExoplanetEU.
Example is `KELT-20 b`, which star name in ExoEU is `HD 185603`, but `KELT-20` in SC.

**Comment by jason-neal** [comment]
Do we need to do a more robust check/match, using "star name" and "alternate name" from exoplanetEU and "star name" and "HD number". I just noticed that on the original Sweet-cat the Simbad link does not always work e.g. for `KELT-20` in your example.

**Comment by jason-neal** [comment]
`pyasl.ExoplanetEU` is now considered deprecated. 
`pyasl.ExoplanetEU2() `is the newer version which downloads the data as a `VOTable` instead of a csv, and gives access to all columns.

From the source the useful columns in ExoplanetEU for this are                                                                           
- name       (Name of a planet )        
- alternate_names (List of planet alternative names)
- star_name                          (Name of a host star) 
- star_alternate_names          (List of star alternative names)     

Of course, not every entry has alternate names listed.

**Comment by DanielAndreasen** [comment]
I have thought some time about this, and in the end I think it is not within the scope. Since we use ExoplanetEU as a reference, we should simply use the same names.
That being said, I did try to compare the planet name (after removing the b, c, d, etc. from the name) with SC. In both cases making the names lower case and removing spaces. This helped a bit (more matches when merged)

**Comment by DanielAndreasen** [comment]
Can you open another issue with switching to ExoplanetEU2?

**Comment by jason-neal** [comment]
I had thought of suggesting the maybe SC just needs to change the names it assigns the stars/planets.

**Comment by DanielAndreasen** [comment]
Okay, I put it in my notes for the SC meeting in September. So I think we can merge #30 and close this issue now.
