### ISSUE TITLE
ValueError when plotting  m_i

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#38]
When trying to plot `mag_i` in the histograms it returns an error.

`ValueError: `bins` should be a positive integer.`

(It it not due to the ExoplanetEU2)

**Comment by jason-neal** [comment]
`Discovered ` vs `mag_i `returns
Possibly there is no data to plot?
```
builtins.ValueError
ValueError: max() arg is an empty sequence
```

**Comment by DanielAndreasen** [comment]
Try change the axis for to linear.

**Comment by DanielAndreasen** [comment]
For the first error: `bins should be a positive number`, it comes from `int(num_points/50)`. Basically this happens when there are very few points.
A fix can be to always have at least 5 bins or some other small number, so: `bins = max([5, int(num_points/50)])`. Or simple don't make the histograms if `int(num_points/50)` is less than 1.

**Comment by jason-neal** [comment]
`mag_i` axis to linear helped for  `Discovered` vs `mag_i`, 

But setting the bins to minimum 5 seems to have fixed most of it. (even log scaling)
