### ISSUE TITLE
Hover parameter information over column headers.

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#88]
Maybe it would be possible to hover the parameter information over the columns. 

e.g. A description, and the units (if any).

Vmag: Visual apparent magnitude
feh: Metallicity, dex

**Comment by DanielAndreasen** [comment]
I think this can be made relatively easy in the HTML. I will have a look later.

**Comment by DanielAndreasen** [comment]
Should be working now with the commit referenced above.
One thing to notice is that I removed part of the test (if the column names are in the data). This is manually added, and should not change with any updates (unless we decide to remove/add columns). The test failed since I updated the names to look better: `[Fe/H]` instead of `feh`.
